### ISSUE TITLE
Add Use Cases to the docs

### ISSUE THREAD

**Issue by AtHeartEngineer** [Rate-Limiting-Nullifier/rln-docs#2]
Add use cases that are being explored, or ideas of how RLN could be used.

**Published version**
[https://rate-limiting-nullifier.github.io/rln-docs/uses.html](https://rate-limiting-nullifier.github.io/rln-docs/uses.html)

**File to edit**
[https://github.com/Rate-Limiting-Nullifier/rln-docs/blob/main/src/uses.md](https://github.com/Rate-Limiting-Nullifier/rln-docs/blob/main/src/uses.md)

**Comment by curryrasul** [comment]
I'm closing this issue for now; we'll add new uses over time.
